version: '3'
services:
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis'
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules  # bookmark to ensure node_modules in container doesn't get overwritten/deleted when mapping
      - ./server:/app
    environment:
      - REDIS_HOST=redis  # service name resolves to the container's hostname: www.docs.docker.com/compose/networking
      - REDIS_PORT=6379  # default port
      - PGUSER=postgres  # default user
      - PGHOST=postgres  # service name
      - PGDATABASE=postgres  # default db
      - PGPASSWORD=postgres_password  # default pw
      - PGPORT=5432  # default port
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis  # service name
      - REDIS_PORT=6379  # default port
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
    - "3050:80"
